controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joints_position_controller:
      type: position_controllers/JointGroupPositionController

trajectory_controller:
  ros__parameters:
    joints:
      - left_hip_pitch_joint
      - left_hip_roll_joint
      - left_knee_joint
      - right_hip_pitch_joint
      - right_hip_roll_joint
      - right_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

joints_position_controller:
  ros__parameters:
    joints:
      - left_hip_pitch_joint
      - left_hip_roll_joint
      - left_knee_joint
      - right_hip_pitch_joint
      - right_hip_roll_joint
      - right_knee_joint



